import type { Metadata } from "next";
import Link from "next/link";
import Wordmark from "@/components/Wordmark";
import Footer from "@/components/sections/Footer";

export const metadata: Metadata = {
  title: "Privacy Policy — Orenara",
  description:
    "How Orenara collects, uses, stores, and protects the personal information you provide through our enquiry form, trade enquiry form, and quote builder, in line with the Australian Privacy Principles.",
  robots: { index: true, follow: true },
};

type Clause = {
  id: string;
  strong?: string;
  text?: string;
  sub?: string[];
};

type Section = {
  n: string;
  title: string;
  clauses: Clause[];
};

const LAST_UPDATED = "3 July 2026";

const sections: Section[] = [
  {
    n: "1",
    title: "Who We Are",
    clauses: [
      {
        id: "1.1",
        text: 'Orenara ("we," "us," "our") supplies outdoor LED strip lighting products to customers and trade professionals across Australia. This policy explains how we handle personal information collected through orenara.com.au, including our general enquiry form, our trade enquiry form, and our quote builder tool.',
      },
      {
        id: "1.2",
        text: "We handle personal information in line with the Australian Privacy Principles (APPs) under the Privacy Act 1988 (Cth). If you have any questions about this policy or how we handle your information, contact us at hello@orenara.com.",
      },
    ],
  },
  {
    n: "2",
    title: "What Personal Information We Collect",
    clauses: [
      {
        id: "2.1",
        strong: "Information you give us directly, through: ",
        text: "",
        sub: [
          "General enquiry form — name, email address, phone number (optional), suburb/state, kit of interest, project timeline, and any message you include.",
          "Trade enquiry form — name, business/trade name, email address, phone number (optional), site delivery suburb/postcode, colour/glow requirements, approximate run lengths, deadline, and any additional details you include.",
          "Quote builder — the zone and run details you enter (lengths, shapes, mounting types) are used to calculate a bill of materials. If you choose to email a quote to us, that breakdown is submitted along with your contact details from the enquiry form.",
        ],
      },
      {
        id: "2.2",
        strong: "Information collected automatically: ",
        text: "when you submit a form, our server records the IP address the submission came from and a timestamp, for security and spam-prevention purposes.",
      },
      {
        id: "2.3",
        text: "We do not currently use advertising cookies, tracking pixels, or third-party analytics scripts on this website. If that changes — for example, if we add Google Ads conversion tracking or a Meta Pixel — we will update this policy to describe what is collected and how you can opt out.",
      },
    ],
  },
  {
    n: "3",
    title: "Why We Collect and Use Your Information",
    clauses: [
      {
        id: "3.1",
        text: "We use the personal information you provide to:",
        sub: [
          "respond to your enquiry with pricing, product information, and lead times;",
          "prepare and follow up on quotes, including the bill of materials generated by the quote builder;",
          "arrange delivery of Products you order;",
          "keep records of our communications with you; and",
          "improve our website and the accuracy of our quoting tools.",
        ],
      },
      {
        id: "3.2",
        text: "We do not use your information for unrelated marketing without your consent, and we do not sell your personal information to any third party.",
      },
    ],
  },
  {
    n: "4",
    title: "Who We Share Your Information With",
    clauses: [
      {
        id: "4.1",
        strong: "Email delivery. ",
        text: "We use Resend, a transactional email service, to send enquiry notifications to our team and to communicate with you by email.",
      },
      {
        id: "4.2",
        strong: "Hosting and infrastructure. ",
        text: "Our website and the servers that process form submissions are hosted by Vercel.",
      },
      {
        id: "4.3",
        text: "We do not disclose your personal information to any other third party except where required by law, or with your consent.",
      },
    ],
  },
  {
    n: "5",
    title: "Overseas Disclosure",
    clauses: [
      {
        id: "5.1",
        text: "The service providers listed in Section 4 may store or process data on servers located outside Australia, including in the United States. By submitting a form on this website, you consent to your personal information being handled by these providers as part of the ordinary operation of our enquiry and quoting process.",
      },
    ],
  },
  {
    n: "6",
    title: "Data Storage and Security",
    clauses: [
      {
        id: "6.1",
        text: "We take reasonable steps to protect the personal information we hold from misuse, interference, loss, and unauthorised access, modification, or disclosure. Form submissions are transmitted over an encrypted connection (HTTPS).",
      },
      {
        id: "6.2",
        text: "No method of electronic storage or transmission is completely secure, and we cannot guarantee absolute security.",
      },
    ],
  },
  {
    n: "7",
    title: "How Long We Keep Your Information",
    clauses: [
      {
        id: "7.1",
        text: "We retain enquiry and quote records for as long as reasonably necessary to respond to your enquiry, fulfil an order, and meet our record-keeping and legal obligations. If you would like us to delete your information sooner, contact us and we will action your request unless we are required to retain it by law.",
      },
    ],
  },
  {
    n: "8",
    title: "Your Rights",
    clauses: [
      {
        id: "8.1",
        text: "Under the Australian Privacy Principles, you have the right to:",
        sub: [
          "ask us what personal information we hold about you and request a copy of it;",
          "ask us to correct any information that is inaccurate, out of date, or incomplete; and",
          "make a complaint if you believe we have mishandled your personal information.",
        ],
      },
      {
        id: "8.2",
        text: "To exercise any of these rights, contact us at hello@orenara.com. If you are not satisfied with our response, you may lodge a complaint with the Office of the Australian Information Commissioner (OAIC) at oaic.gov.au.",
      },
    ],
  },
  {
    n: "9",
    title: "Children's Information",
    clauses: [
      {
        id: "9.1",
        text: "Our website and services are directed at adults arranging outdoor lighting for their homes or trade projects. We do not knowingly collect personal information from children.",
      },
    ],
  },
  {
    n: "10",
    title: "Changes to This Policy",
    clauses: [
      {
        id: "10.1",
        text: "We may update this policy from time to time to reflect changes in our practices or for legal or operational reasons. The date at the top of this page shows when it was last updated. Continued use of our website after an update means you accept the revised policy.",
      },
    ],
  },
  {
    n: "11",
    title: "Contact Us",
    clauses: [
      {
        id: "11.1",
        text: "If you have any questions about this Privacy Policy or how we handle your personal information, email us at hello@orenara.com.",
      },
    ],
  },
];

export default function PrivacyPage() {
  return (
    <>
      {/* Header */}
      <header
        className="fixed top-0 left-0 right-0 z-50"
        style={{
          background: "linear-gradient(180deg, rgba(21,23,28,0.97) 0%, rgba(21,23,28,0.0) 100%)",
        }}
      >
        <nav className="max-w-7xl mx-auto px-6 py-5 flex items-center justify-between">
          <Link href="/" style={{ textDecoration: "none", display: "inline-flex" }} aria-label="Orenara home">
            <Wordmark size="sm" />
          </Link>
          <Link
            href="/"
            className="hidden sm:inline-flex"
            style={{ color: "#9A9DA8", fontSize: "0.875rem", fontWeight: 500, textDecoration: "none" }}
            data-testid="privacy-back-link"
          >
            Back to site
          </Link>
        </nav>
      </header>

      <main style={{ background: "#15171C" }}>
        <section style={{ paddingTop: "148px", paddingBottom: "80px" }}>
          <div className="mx-auto px-6" style={{ maxWidth: "820px" }}>
            <p className="spec-badge mb-6" style={{ display: "inline-flex" }}>
              Legal
            </p>
            <h1
              className="font-bold"
              style={{
                fontSize: "clamp(2rem, 5vw, 3.25rem)",
                color: "#F4F1EA",
                letterSpacing: "-0.035em",
                lineHeight: 1.08,
              }}
            >
              Privacy <span className="text-gradient-amber">Policy</span>
            </h1>
            <p style={{ marginTop: "16px", fontSize: "0.875rem", color: "#5B6478" }}>
              Last updated: {LAST_UPDATED}
            </p>

            {/* Summary callout */}
            <div
              style={{
                marginTop: "32px",
                padding: "20px 24px",
                borderRadius: "12px",
                border: "1px solid rgba(245,178,92,0.25)",
                background: "rgba(245,178,92,0.06)",
              }}
            >
              <p style={{ fontSize: "0.9375rem", color: "#F4F1EA", lineHeight: 1.7, fontWeight: 600 }}>
                We only collect what we need to quote your job and get back to you.
              </p>
              <p style={{ marginTop: "6px", fontSize: "0.9375rem", color: "#9A9DA8", lineHeight: 1.7 }}>
                We never sell your personal information, and we don&apos;t use it for marketing you
                haven&apos;t agreed to.
              </p>
            </div>

            {/* Sections */}
            <div style={{ marginTop: "48px" }}>
              {sections.map((section) => (
                <section key={section.n} style={{ marginBottom: "44px" }}>
                  <h2
                    className="font-bold"
                    style={{
                      fontSize: "clamp(1.25rem, 3vw, 1.6rem)",
                      color: "#F4F1EA",
                      letterSpacing: "-0.02em",
                      lineHeight: 1.25,
                      marginBottom: "20px",
                      paddingBottom: "12px",
                      borderBottom: "1px solid rgba(91,100,120,0.2)",
                    }}
                  >
                    <span style={{ color: "#F5B25C", marginRight: "12px" }}>{section.n}.</span>
                    {section.title}
                  </h2>

                  {section.clauses.map((clause) => (
                    <div key={clause.id} style={{ marginBottom: "18px" }}>
                      <p style={{ fontSize: "0.9375rem", color: "#C9CCD4", lineHeight: 1.75 }}>
                        <span
                          style={{
                            color: "#5B6478",
                            fontWeight: 700,
                            fontVariantNumeric: "tabular-nums",
                            marginRight: "10px",
                          }}
                        >
                          {clause.id}
                        </span>
                        {clause.strong ? (
                          <strong style={{ color: "#F4F1EA", fontWeight: 700 }}>{clause.strong}</strong>
                        ) : null}
                        {clause.text}
                      </p>
                      {clause.sub ? (
                        <div style={{ marginTop: "10px", paddingLeft: "28px" }}>
                          {clause.sub.map((item, i) => (
                            <p
                              key={i}
                              style={{
                                fontSize: "0.9375rem",
                                color: "#9A9DA8",
                                lineHeight: 1.75,
                                marginBottom: "8px",
                              }}
                            >
                              {item}
                            </p>
                          ))}
                        </div>
                      ) : null}
                    </div>
                  ))}
                </section>
              ))}
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </>
  );
}
