// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-preview/NewHero.tsx": () => import("../components/mockups/hero-preview/NewHero.tsx"),
  "./components/mockups/hero-preview/StripGlowPreview.tsx": () => import("../components/mockups/hero-preview/StripGlowPreview.tsx"),
  "./components/mockups/orenara-og/OgImage.tsx": () => import("../components/mockups/orenara-og/OgImage.tsx"),
  "./components/mockups/raycor-rebrand/Hero.tsx": () => import("../components/mockups/raycor-rebrand/Hero.tsx"),
  "./components/mockups/orenara-product/FlatLay.tsx": () => import("../components/mockups/orenara-product/FlatLay.tsx"),
  "./components/mockups/orenara-product/SplitPanel.tsx": () => import("../components/mockups/orenara-product/SplitPanel.tsx")
};
